config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :facilities

  resources :communities

  resources :positions

  devise_for :users
  resources :people

  resources :tasks

  root 'home#index'
  resources :teams

  resources :orgs

  resources :zones

  namespace :api do
    resources :communities, defaults: { format: :json }
    resources :facilities,  defaults: { format: :json }
    resources :people,      defaults: { format: :json }
    resources :teams,       defaults: { format: :json }
    resources :zones,       defaults: { format: :json }

  end

end

app/models/position.rb
class Position < ActiveRecord::Base
  has_and_belongs_to_many :people
  validates :name, :uniqueness => true
  def self.db_seed
    [
      'Com Liaison',
      'Monitor',
      'Program staff',
      'Psycho Officer',
      'Supervisor',
      'Zone manager'
    ].each do |task|
      Position.create!(name: task)
    end
  end

end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render json: @position, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:name, :description)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.haml
= bootstrap_form_for @position do |f|
  - if @position.errors.any?
    #error_explanation
      %h2= "#{pluralize(@position.errors.count, "error")} prohibited this position from being saved:"
      %ul
        - @position.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_field :name
  .field
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/positions/edit.html.haml
%h1 Editing position

= render 'form'

= link_to 'Show', @position
\|
= link_to 'Back', positions_path

app/views/positions/index.html.haml
%h1 Listing positions

%table
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th
      
  %tbody
    - @positions.each do |position|
      %tr
        %td= position.name
        %td= position.description
        %td= link_to 'Show', position
        %td= link_to 'Edit', edit_position_path(position)
        %td= link_to 'Destroy', position, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Position', new_position_path

app/views/positions/new.html.haml
%h1 New position

= render 'form'

= link_to 'Back', positions_path

app/views/positions/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @position.name
%p
  %b Description:
  = @position.description

= link_to 'Edit', edit_position_path(@position)
\|
= link_to 'Back', positions_path