config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :facilities

  resources :communities

  resources :positions

  devise_for :users
  resources :people

  resources :tasks

  root 'home#index'
  resources :teams

  resources :orgs

  resources :zones

  namespace :api do
    resources :communities, defaults: { format: :json }
    resources :facilities,  defaults: { format: :json }
    resources :people,      defaults: { format: :json }
    resources :teams,       defaults: { format: :json }
    resources :zones,       defaults: { format: :json }

  end

end

app/models/zone.rb
require 'rake'  
class Zone < ActiveRecord::Base
  has_and_belongs_to_many :teams, :join_table => "teams_zones"
  

  def self.zone_table
    [
      {'1100A2'   => 'Paynseville ELWA'},
      {'1100A1'   => 'Paynseville Duport Road'},
      {'1100B1'   => 'Paynseville Peace'},
      {'1100B2'   => 'Paynseville Pipeline'},
      {'1000' => 'Congo Town'},
      {'900'  => 'Old Road'},
      {'800'  => 'Lakpazee'},
      {'700'  => 'Sinkor'},
      {'600'  => 'Slipway'},
      {'500'  => 'Soniwein'},
      {'400'  => 'West Point'},
      {'300'  => 'Clara Town'},
      {'200'  => 'Logan Town'},
      {'100'  => 'New Kru Town'},
      {'1200' => 'Gardnersville'},
      {'1300' => 'New Georgia'},
      {'1400' => 'Barnesville'},
      {'1500' => 'Common-wealth'},
      {'1600' => 'Caldwell'},
      {'1700' => 'Careysburg'},
      {'1800' => 'Todee'},
      {'1900' => 'St. Paul'},
    ]

  end

  def self.seed_data
    Zone.zone_table.each do |e|
      Zone.create!(epi_code: e.keys[0], cnam: e.values[0]) 
    end
  end

  def self.zone_hash
    Zone.zone_table.inject({}){|h, z| h[z.keys[0]] = z.values[0]; h}
  end
end

app/controllers/api/zones_controller.rb
class Api::ZonesController < ApplicationController
  respond_to :json

  def index
  	sleep 1
    #render json: Zone.zone_table
      serialized_zones =
        ActiveModel::ArraySerializer
                 .new(Zone.all, each_serializer: ZoneSerializer)

      render json: serialized_zones
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]
  before_action :is_authorized?
  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to zones_url, notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:description, :name, :objectID, :epi_code, :shape_leng, :shape_area, :cnam, :geometry)
    end
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/zones/_form.html.haml
= bootstrap_form_for @zone do |f|
  - if @zone.errors.any?
    #error_explanation
      %h2= "#{pluralize(@zone.errors.count, "error")} prohibited this zone from being saved:"
      %ul
        - @zone.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_area :description
  .field
    = f.text_field :name
  .field
    = f.number_field :objectID
  .field
    = f.text_field :epi_code
  .field
    = f.text_field :shape_leng
  .field
    = f.text_field :shape_area
  .field
    = f.text_field :cnam
  .field
    = f.text_field :geometry
  .actions
    = f.submit 'Save'

app/views/zones/edit.html.haml
%h1 Editing zone

= render 'form'

= link_to 'Show', @zone
\|
= link_to 'Back', zones_path

app/views/zones/index.html.haml
%h1 Listing zones

%table.table
  %thead
    %tr
      %th Description
      %th Name
      %th Objectid
      %th Epi code
      %th Shape leng
      %th Shape area
      %th Cnam
      %th Geometry
      %th
      %th
      %th
      
  %tbody
    - @zones.each do |zone|
      %tr
        %td= zone.description
        %td= zone.name
        %td= zone.objectID
        %td= zone.epi_code
        %td= zone.shape_leng
        %td= zone.shape_area
        %td= zone.cnam
        %td= zone.geometry
        %td= link_to 'Show', zone
        %td= link_to 'Edit', edit_zone_path(zone)
        %td= link_to 'Destroy', zone, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Zone', new_zone_path

app/views/zones/new.html.haml
%h1 New zone

= render 'form'

= link_to 'Back', zones_path

app/views/zones/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @zone.description
%p
  %b Name:
  = @zone.name
%p
  %b Objectid:
  = @zone.objectID
%p
  %b Epi code:
  = @zone.epi_code
%p
  %b Shape leng:
  = @zone.shape_leng
%p
  %b Shape area:
  = @zone.shape_area
%p
  %b Cnam:
  = @zone.cnam
%p
  %b Geometry:
  = @zone.geometry

= link_to 'Edit', edit_zone_path(@zone)
\|
= link_to 'Back', zones_path